In [1]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('IMDB-Movie-Data.csv')
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [26]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [20]:
genre=[df['Genre']]
for i in genre:
    print(i)
    print('\n')

0       Action,Adventure,Sci-Fi
1      Adventure,Mystery,Sci-Fi
2               Horror,Thriller
3       Animation,Comedy,Family
4      Action,Adventure,Fantasy
                 ...
995         Crime,Drama,Mystery
996                      Horror
997         Drama,Music,Romance
998            Adventure,Comedy
999       Comedy,Family,Fantasy
Name: Genre, Length: 1000, dtype: object

In [16]:
favourite_director_movies=df['Director']=='Christopher Nolan'
df[favourite_director_movies]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
36,37,Interstellar,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
54,55,The Dark Knight,"Action,Crime,Drama",When the menace known as the Joker wreaks havo...,Christopher Nolan,"Christian Bale, Heath Ledger, Aaron Eckhart,Mi...",2008,152,9.0,1791916,533.32,82.0
64,65,The Prestige,"Drama,Mystery,Sci-Fi",Two stage magicians engage in competitive one-...,Christopher Nolan,"Christian Bale, Hugh Jackman, Scarlett Johanss...",2006,130,8.5,913152,53.08,66.0
80,81,Inception,"Action,Adventure,Sci-Fi","A thief, who steals corporate secrets through ...",Christopher Nolan,"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen...",2010,148,8.8,1583625,292.57,74.0
124,125,The Dark Knight Rises,"Action,Thriller",Eight years after the Joker's reign of anarchy...,Christopher Nolan,"Christian Bale, Tom Hardy, Anne Hathaway,Gary ...",2012,164,8.5,1222645,448.13,78.0

In [23]:
movies_with_7_rating=df['Rating']==7
df[movies_with_7_rating]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
9,10,Passengers,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0
58,59,Their Finest,"Comedy,Drama,Romance","A former secretary, newly appointed as a scrip...",Lone Scherfig,"Gemma Arterton, Sam Claflin, Bill Nighy, Jack ...",2016,117,7.0,3739,3.18,76.0
85,86,Jurassic World,"Action,Adventure,Sci-Fi","A new theme park, built on the original site o...",Colin Trevorrow,"Chris Pratt, Bryce Dallas Howard, Ty Simpkins,...",2015,124,7.0,455169,652.18,59.0
91,92,Warcraft,"Action,Adventure,Fantasy",As an Orc horde invades the planet Azeroth usi...,Duncan Jones,"Travis Fimmel, Paula Patton, Ben Foster, Domin...",2016,123,7.0,187547,47.17,32.0
100,101,Legend,"Biography,Crime,Drama",Identical twin gangsters Ronald and Reginald K...,Brian Helgeland,"Tom Hardy, Emily Browning, Taron Egerton, Paul...",2015,132,7.0,108836,1.87,55.0
101,102,Thor,"Action,Adventure,Fantasy",The powerful but arrogant god Thor is cast out...,Kenneth Branagh,"Chris Hemsworth, Anthony Hopkins, Natalie Port...",2011,115,7.0,570814,181.02,57.0
156,157,Pacific Rim,"Action,Adventure,Sci-Fi",As a war between humankind and monstrous sea c...,Guillermo del Toro,"Idris Elba, Charlie Hunnam, Rinko Kikuchi,Char...",2013,131,7.0,400519,101.79,64.0
161,162,Free Fire,"Action,Comedy,Crime","Set in Boston in 1978, a meeting in a deserted...",Ben Wheatley,"Sharlto Copley, Brie Larson, Armie Hammer, Cil...",2016,90,7.0,6946,1.80,63.0
177,178,Tropic Thunder,"Action,Comedy","Through a series of freak occurrences, a group...",Ben Stiller,"Ben Stiller, Jack Black, Robert Downey Jr., Je...",2008,107,7.0,321442,110.42,71.0
182,183,Cinderella,"Drama,Family,Fantasy","When her father unexpectedly passes away, youn...",Kenneth Branagh,"Lily James, Cate Blanchett, Richard Madden,Hel...",2015,105,7.0,117018,201.15,67.0
214,215,Thor: The Dark World,"Action,Adventure,Fantasy",When Dr. Jane Foster gets cursed with a powerf...,Alan Taylor,"Chris Hemsworth, Natalie Portman, Tom Hiddlest...",2013,112,7.0,443584,206.36,54.0
224,225,We're the Millers,"Comedy,Crime",A veteran pot dealer creates a fake family as ...,Rawson Marshall Thurber,"Jason Sudeikis, Jennifer Aniston, Emma Roberts...",2013,110,7.0,334867,150.37,44.0
225,226,American Honey,Drama,A teenage girl with nothing to lose joins a tr...,Andrea Arnold,"Sasha Lane, Shia LaBeouf, Riley Keough, McCaul...",2016,163,7.0,19660,0.66,79.0
228,229,Maleficent,"Action,Adventure,Family",A vengeful fairy is driven to curse an infant ...,Robert Stromberg,"Angelina Jolie, Elle Fanning, Sharlto Copley,L...",2014,97,7.0,268877,241.41,56.0
263,264,Nymphomaniac: Vol. I,Drama,A self-diagnosed nymphomaniac recounts her ero...,Lars von Trier,"Charlotte Gainsbourg, Stellan Skarsgård, Stacy...",2013,117,7.0,90556,0.79,64.0
275,276,Oblivion,"Action,Adventure,Mystery",A veteran assigned to extract Earth's remainin...,Joseph Kosinski,"Tom Cruise, Morgan Freeman, Andrea Riseborough...",2013,124,7.0,410125,89.02,54.0
278,279,Everybody Wants Some!!,Comedy,"In 1980, a group of college baseball players n...",Richard Linklater,"Blake Jenner, Tyler Hoechlin, Ryan Guzman,Zoey...",2016,117,7.0,36312,3.37,83.0
283,284,The Danish Girl,"Biography,Drama,Romance",A fictitious love story loosely inspired by th...,Tom Hooper,"Eddie Redmayne, Alicia Vikander, Amber Heard, ...",2015,119,7.0,110773,12.71,66.0
302,303,The Cabin in the Woods,Horror,"Five friends go for a break at a remote cabin,...",Drew Goddard,"Kristen Connolly, Chris Hemsworth, Anna Hutchi...",2012,95,7.0,295554,42.04,72.0
315,316,Snowpiercer,"Action,Drama,Sci-Fi",Set in a future where a failed climate-change ...,Bong Joon Ho,"Chris Evans, Jamie Bell, Tilda Swinton, Ed Harris",2013,126,7.0,199048,4.56,84.0
328,329,Green Room,"Crime,Horror,Thriller",A punk rock band is forced to fight for surviv...,Jeremy Saulnier,"Anton Yelchin, Imogen Poots, Alia Shawkat,Patr...",2015,95,7.0,62885,3.22,79.0
368,369,The Amazing Spider-Man,"Action,Adventure",After Peter Parker is bitten by a genetically ...,Marc Webb,"Andrew Garfield, Emma Stone, Rhys Ifans, Irrfa...",2012,136,7.0,474320,262.03,66.0
432,433,World War Z,"Action,Adventure,Horror",Former United Nations employee Gerry Lane trav...,Marc Forster,"Brad Pitt, Mireille Enos, Daniella Kertesz, Ja...",2013,116,7.0,494819,202.35,63.0
450,451,Iron Man 2,"Action,Adventure,Sci-Fi",With the world now aware of his identity as Ir...,Jon Favreau,"Robert Downey Jr., Mickey Rourke, Gwyneth Palt...",2010,124,7.0,556666,312.06,57.0
451,452,Demolition,"Comedy,Drama",A successful investment banker struggles after...,Jean-Marc Vallée,"Jake Gyllenhaal, Naomi Watts, Chris Cooper,Jud...",2015,101,7.0,58720,1.82,49.0
492,493,Cloverfield,"Action,Horror,Sci-Fi",A group of friends venture deep into the stree...,Matt Reeves,"Mike Vogel, Jessica Lucas, Lizzy Caplan, T.J. ...",2008,85,7.0,313803,80.03,64.0
524,525,Trust,"Crime,Drama,Thriller",A teenage girl is targeted by an online sexual...,David Schwimmer,"Clive Owen, Catherine Keener, Liana Liberato,J...",2010,106,7.0,36043,0.06,60.0
532,533,Deja Vu,"Action,Sci-Fi,Thriller","After a ferry is bombed in New Orleans, an A.T...",Tony Scott,"Denzel Washington, Paula Patton, Jim Caviezel,...",2006,126,7.0,253858,NaN,NaN
536,537,Jack Reacher,"Action,Crime,Mystery",A homicide investigator digs deeper into a cas...,Christopher McQuarrie,"Tom Cruise, Rosamund Pike, Richard Jenkins, We...",2012,130,7.0,250811,58.68,50.0
609,610,Hellboy II: The Golden Army,"Action,Adventure,Fantasy",The mythical world starts a rebellion against ...,Guillermo del Toro,"Ron Perlman, Selma Blair, Doug Jones, John Ale...",2008,120,7.0,216932,75.75,78.0
632,633,The Host,"Comedy,Drama,Horror",A monster emerges from Seoul's Han River and f...,Bong Joon Ho,"Kang-ho Song, Hee-Bong Byun, Hae-il Park, Doon...",2006,120,7.0,73491,2.20,85.0
635,636,Knocked Up,"Comedy,Romance","For fun-loving party animal Ben Stone, the las...",Judd Apatow,"Seth Rogen, Katherine Heigl, Paul Rudd, Leslie...",2007,129,7.0,309398,148.73,85.0
655,656,Public Enemies,"Biography,Crime,Drama",The Feds try to take down notorious American g...,Michael Mann,"Christian Bale, Johnny Depp, Christian Stolte,...",2009,140,7.0,240323,97.03,70.0
660,661,Pineapple Express,"Action,Comedy,Crime",A process server and his marijuana dealer wind...,David Gordon Green,"Seth Rogen, James Franco, Gary Cole, Danny McB...",2008,111,7.0,267872,87.34,64.0
701,702,Ted,"Comedy,Fantasy","John Bennett, a man whose childhood wish of br...",Seth MacFarlane,"Mark Wahlberg, Mila Kunis, Seth MacFarlane, Jo...",2012,106,7.0,494641,218.63,62.0
731,732,Paul,"Adventure,Comedy,Sci-Fi",Two British comic-book geeks traveling across ...,Greg Mottola,"Simon Pegg, Nick Frost, Seth Rogen, Mia Stallard",2011,104,7.0,201707,37.37,57.0
799,800,The World's End,"Action,Comedy,Sci-Fi",Five friends who reunite in an attempt to top ...,Edgar Wright,"Simon Pegg, Nick Frost, Martin Freeman, Rosamu...",2013,109,7.0,199813,26.00,81.0
812,813,Orphan,"Horror,Mystery,Thriller",A husband and wife who recently lost their bab...,Jaume Collet-Serra,"Vera Farmiga, Peter Sarsgaard, Isabelle Fuhrma...",2009,123,7.0,153448,41.57,42.0
823,824,Christine,"Biography,Drama","The story of Christine Chubbuck, a 1970s TV re...",Antonio Campos,"Rebecca Hall, Michael C. Hall, Tracy Letts, Ma...",2016,119,7.0,5855,0.30,72.0
873,874,One Day,"Drama,Romance",After spending the night together on the night...,Lone Scherfig,"Anne Hathaway, Jim Sturgess, Patricia Clarkson...",2011,107,7.0,113599,13.77,48.0
875,876,28 Weeks Later,"Drama,Horror,Sci-Fi",Six months after the rage virus was inflicted ...,Juan Carlos Fresnadillo,"Jeremy Renner, Rose Byrne, Robert Carlyle, Har...",2007,100,7.0,221858,28.64,78.0
960,961,Trance,"Crime,Drama,Mystery",An art auctioneer who has become mixed up with...,Danny Boyle,"James McAvoy, Rosario Dawson, Vincent Cassel,D...",2013,101,7.0,97141,2.32,61.0
965,966,Inland Empire,"Drama,Mystery,Thriller",As an actress starts to adopt the persona of h...,David Lynch,"Laura Dern, Jeremy Irons, Justin Theroux, Karo...",2006,180,7.0,44227,NaN,NaN
978,979,It's Only the End of the World,Drama,"Louis (Gaspard Ulliel), a terminally ill write...",Xavier Dolan,"Nathalie Baye, Vincent Cassel, Marion Cotillar...",2016,97,7.0,10658,NaN,48.0
980,981,Miracles from Heaven,"Biography,Drama,Family",A young girl suffering from a rare digestive d...,Patricia Riggen,"Jennifer Garner, Kylie Rogers, Martin Henderso...",2016,109,7.0,12048,61.69,44.0